FROM golang:1.26 AS build

ARG VERSION=dev

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags "-X main.Version=$VERSION" -o /maddock-server ./cmd/server/

FROM alpine:3.23

COPY --from=build /maddock-server /usr/local/bin/maddock-server
ENTRYPOINT ["maddock-server"]
