baseURL = "https://madjlzz.github.io/maddock/"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "Maddock"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = "Maddock is a `configuration as code` tool that let Ops describe a machine fleet's state."
  homepage_image = 'images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Maddock is a `configuration as code` tool that let Ops describe a machine fleet's state."
    meta_og_title = "Maddock"
    meta_og_type = "website"
    meta_og_url = "https://madjlzz.github.io/maddock/"
    meta_og_image = ""
    meta_og_description = "Maddock is a `configuration as code` tool that let Ops describe a machine fleet's state."
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = ""

  [params.logo]
      mobile = "images/logo-mobile.svg"
      standard  = "images/logo.svg"

  [params.footer]
    copyright_text = 'Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">Zerostatic Themes</a>'
