// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: internal/transport/proto/maddock.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_OK      State = 0
	State_STATE_CHANGED State = 1
	State_STATE_FAILED  State = 2
	State_STATE_SKIPPED State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_OK",
		1: "STATE_CHANGED",
		2: "STATE_FAILED",
		3: "STATE_SKIPPED",
	}
	State_value = map[string]int32{
		"STATE_OK":      0,
		"STATE_CHANGED": 1,
		"STATE_FAILED":  2,
		"STATE_SKIPPED": 3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_proto_maddock_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_internal_transport_proto_maddock_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_proto_maddock_proto_rawDescGZIP(), []int{0}
}

type CatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestName  string                 `protobuf:"bytes,1,opt,name=manifest_name,json=manifestName,proto3" json:"manifest_name,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Resources     []*ResourceMsg         `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogRequest) Reset() {
	*x = CatalogRequest{}
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogRequest) ProtoMessage() {}

func (x *CatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogRequest.ProtoReflect.Descriptor instead.
func (*CatalogRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_maddock_proto_rawDescGZIP(), []int{0}
}

func (x *CatalogRequest) GetManifestName() string {
	if x != nil {
		return x.ManifestName
	}
	return ""
}

func (x *CatalogRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *CatalogRequest) GetResources() []*ResourceMsg {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ResourceMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`             // "package", "file", "service"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`             // "nginx", "/etc/nginx/nginx.conf"
	Attributes    []byte                 `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"` // JSON-encoded attributes map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMsg) Reset() {
	*x = ResourceMsg{}
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMsg) ProtoMessage() {}

func (x *ResourceMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMsg.ProtoReflect.Descriptor instead.
func (*ResourceMsg) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_maddock_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceMsg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceMsg) GetAttributes() []byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ResourceReportMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         State                  `protobuf:"varint,3,opt,name=state,proto3,enum=maddock.v1.State" json:"state,omitempty"`
	Changes       []*DifferenceMsg       `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceReportMsg) Reset() {
	*x = ResourceReportMsg{}
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceReportMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReportMsg) ProtoMessage() {}

func (x *ResourceReportMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReportMsg.ProtoReflect.Descriptor instead.
func (*ResourceReportMsg) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_maddock_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceReportMsg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceReportMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceReportMsg) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_OK
}

func (x *ResourceReportMsg) GetChanges() []*DifferenceMsg {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ResourceReportMsg) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResourceReportMsg) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type DifferenceMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     string                 `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Current       string                 `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	Desired       string                 `protobuf:"bytes,3,opt,name=desired,proto3" json:"desired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifferenceMsg) Reset() {
	*x = DifferenceMsg{}
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifferenceMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifferenceMsg) ProtoMessage() {}

func (x *DifferenceMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifferenceMsg.ProtoReflect.Descriptor instead.
func (*DifferenceMsg) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_maddock_proto_rawDescGZIP(), []int{3}
}

func (x *DifferenceMsg) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *DifferenceMsg) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

func (x *DifferenceMsg) GetDesired() string {
	if x != nil {
		return x.Desired
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_maddock_proto_rawDescGZIP(), []int{4}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_maddock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_maddock_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PingResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

var File_internal_transport_proto_maddock_proto protoreflect.FileDescriptor

const file_internal_transport_proto_maddock_proto_rawDesc = "" +
	"\n" +
	"&internal/transport/proto/maddock.proto\x12\n" +
	"maddock.v1\"\x85\x01\n" +
	"\x0eCatalogRequest\x12#\n" +
	"\rmanifest_name\x18\x01 \x01(\tR\fmanifestName\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\x125\n" +
	"\tresources\x18\x03 \x03(\v2\x17.maddock.v1.ResourceMsgR\tresources\"U\n" +
	"\vResourceMsg\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"attributes\x18\x03 \x01(\fR\n" +
	"attributes\"\xd0\x01\n" +
	"\x11ResourceReportMsg\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x05state\x18\x03 \x01(\x0e2\x11.maddock.v1.StateR\x05state\x123\n" +
	"\achanges\x18\x04 \x03(\v2\x19.maddock.v1.DifferenceMsgR\achanges\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"a\n" +
	"\rDifferenceMsg\x12\x1c\n" +
	"\tattribute\x18\x01 \x01(\tR\tattribute\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\tR\acurrent\x12\x18\n" +
	"\adesired\x18\x03 \x01(\tR\adesired\"\r\n" +
	"\vPingRequest\"O\n" +
	"\fPingResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion*M\n" +
	"\x05State\x12\f\n" +
	"\bSTATE_OK\x10\x00\x12\x11\n" +
	"\rSTATE_CHANGED\x10\x01\x12\x10\n" +
	"\fSTATE_FAILED\x10\x02\x12\x11\n" +
	"\rSTATE_SKIPPED\x10\x032\x96\x01\n" +
	"\fAgentService\x12K\n" +
	"\fApplyCatalog\x12\x1a.maddock.v1.CatalogRequest\x1a\x1d.maddock.v1.ResourceReportMsg0\x01\x129\n" +
	"\x04Ping\x12\x17.maddock.v1.PingRequest\x1a\x18.maddock.v1.PingResponseB5Z3github.com/MadJlzz/maddock/internal/transport/protob\x06proto3"

var (
	file_internal_transport_proto_maddock_proto_rawDescOnce sync.Once
	file_internal_transport_proto_maddock_proto_rawDescData []byte
)

func file_internal_transport_proto_maddock_proto_rawDescGZIP() []byte {
	file_internal_transport_proto_maddock_proto_rawDescOnce.Do(func() {
		file_internal_transport_proto_maddock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_proto_maddock_proto_rawDesc), len(file_internal_transport_proto_maddock_proto_rawDesc)))
	})
	return file_internal_transport_proto_maddock_proto_rawDescData
}

var file_internal_transport_proto_maddock_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_transport_proto_maddock_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_transport_proto_maddock_proto_goTypes = []any{
	(State)(0),                // 0: maddock.v1.State
	(*CatalogRequest)(nil),    // 1: maddock.v1.CatalogRequest
	(*ResourceMsg)(nil),       // 2: maddock.v1.ResourceMsg
	(*ResourceReportMsg)(nil), // 3: maddock.v1.ResourceReportMsg
	(*DifferenceMsg)(nil),     // 4: maddock.v1.DifferenceMsg
	(*PingRequest)(nil),       // 5: maddock.v1.PingRequest
	(*PingResponse)(nil),      // 6: maddock.v1.PingResponse
}
var file_internal_transport_proto_maddock_proto_depIdxs = []int32{
	2, // 0: maddock.v1.CatalogRequest.resources:type_name -> maddock.v1.ResourceMsg
	0, // 1: maddock.v1.ResourceReportMsg.state:type_name -> maddock.v1.State
	4, // 2: maddock.v1.ResourceReportMsg.changes:type_name -> maddock.v1.DifferenceMsg
	1, // 3: maddock.v1.AgentService.ApplyCatalog:input_type -> maddock.v1.CatalogRequest
	5, // 4: maddock.v1.AgentService.Ping:input_type -> maddock.v1.PingRequest
	3, // 5: maddock.v1.AgentService.ApplyCatalog:output_type -> maddock.v1.ResourceReportMsg
	6, // 6: maddock.v1.AgentService.Ping:output_type -> maddock.v1.PingResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_transport_proto_maddock_proto_init() }
func file_internal_transport_proto_maddock_proto_init() {
	if File_internal_transport_proto_maddock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_proto_maddock_proto_rawDesc), len(file_internal_transport_proto_maddock_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_proto_maddock_proto_goTypes,
		DependencyIndexes: file_internal_transport_proto_maddock_proto_depIdxs,
		EnumInfos:         file_internal_transport_proto_maddock_proto_enumTypes,
		MessageInfos:      file_internal_transport_proto_maddock_proto_msgTypes,
	}.Build()
	File_internal_transport_proto_maddock_proto = out.File
	file_internal_transport_proto_maddock_proto_goTypes = nil
	file_internal_transport_proto_maddock_proto_depIdxs = nil
}
