name: Golang

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: jdx/mise-action@v4.0.1

      - name: Build
        run: mise run build

      - name: Lint
        run: mise run lint

      - name: Test
        run: mise run test
